### ISSUE TITLE
Support for `stimulus-decorators`

### ISSUE THREAD

**Issue by Zeko369** [marcoroth/stimulus-parser#10]
[stimulus-decorators](https://github.com/vytant/stimulus-decorators) is a great project bringing [@github/catalyst](https://catalyst.rocks/) typesafe syntax to stimulus

It would be great if we could also parse those libraries but make sure you can mix and match (i.e. static `values` but decorated `@Targets`)

**Comment by marcoroth** [comment]
I 100% agree, this was actually planned. Thanks for putting up the issue 🙌🏼 

I think this is going to be easier to implement as soon as we have support for parsing TypeScript (#9).

**Comment by Zeko369** [comment]
I have both working locally, just need to clean up the decorator part, but will push them up as 2 separate PRs tonight
