### ISSUE TITLE
Public class fields without a default value break the parser

### ISSUE THREAD

**Issue by djfpaagman** [marcoroth/stimulus-parser#20]
I was playing around with the LSP and noticed errors for some of my Stimulus controllers.

Debugging a bit I noticed that the parser fails on them, because we use some empty [public class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields) like so:

```js
import { Controller } from "@hotwired/stimulus";

export default class extends Controller {
  someField;

  // this is just an example how we use them later, not related to the bug
  doSomething() {
    this.someField = "some value";
  }
}
```

* It does work if you set it with a value, like `someField = "initial value"`. 
* Having `static` in front of it also breaks

It fails on this line: https://github.com/marcoroth/stimulus-parser/blob/31842f47cde84ea475f50da8f604b6c6397d7abb/src/parser.ts#L45 with TypeError: Cannot read properties of null (reading 'type')

I guess those nodes don't have a `type`, so some other parsing exception should be added.

 Happy to help, but I don't have a good idea in what direction to go.

_edit later that day:_ I made a PR that implements a possible fix in #21!

**Comment by marcoroth** [comment]
Resolved via #21, thanks!
