### ISSUE TITLE
Error parsing private getters

### ISSUE THREAD

**Issue by mguidetti** [marcoroth/stimulus-parser#31]
An unexpected token error will be raised if a Stimulus controller has a private getter defined, such as:

```
get #activeItems () {
    return this.itemTargets.filter(div => !div.classList.contains('destroying'))
}
```

**Comment by marcoroth** [comment]
Hey @mguidetti, thanks for reporting this. I was able to reproduce this here: https://github.com/marcoroth/stimulus-parser/compare/main...fix-private-getters

I'm not quite sure why this doesn't work though. We are using [`acorn-private-methods`] and [`acorn-class-fields`] which should cover this syntax. I'm wondering if it's time to actually swap out the parser (see #15) so we can better support new ECMAScript features like this.

**Comment by marcoroth** [comment]
Oh, interesting: https://github.com/acornjs/acorn-private-methods/issues/7

**Comment by mguidetti** [comment]
Glad this could help! Thank you!
